name: CI
on:
  push:
jobs:
  test:
    name: Lint & Test & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Packages
        run: npm ci
      - name: Check Lint
        run: npm run lint
      - name: Check TypeScript
        run: npm run lint:type
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Integration
        run: npm run integration:ci
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: testcafe-failure-screenshots
          path: ${{ github.workspace }}/screenshots
          retention-days: 1
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@19.0.5 --branches master
